import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { assertAttestableCapabilities, check, consistency, diff, extract, fileDigest, generatedGuardSource, htmlReport, keygenFiles, loadCatalog, parsePolicyYaml, receipt, replayProof, sourceBinding, verifyReceipt } from "./arsenallint.ts";
const [cmd,...args]=process.argv.slice(2);const flag=(name:string)=>{const i=args.indexOf(name);return i<0?undefined:args[i+1];};const req=(name:string)=>{const v=flag(name);if(!v)throw new Error(`missing ${name}`);return v;};const policy=(p:string)=>parsePolicyYaml(readFileSync(p,"utf8"));const print=(x:unknown)=>console.log(JSON.stringify(x,null,2));const exitFor=(s:string,failWarn=false)=>s==="FAIL"?1:s==="WARN"&&failWarn?1:0;
try { if(cmd==="doctor"){const c=loadCatalog();print({ok:true,node:process.version,provenance:c.provenance});}
else if(cmd==="extract")print(extract(args[0]));
else if(cmd==="diff")print(diff(extract(args[0]),extract(args[1])));
else if(cmd==="check"){const p=policy(args[0]),c=loadCatalog(),v=check(p,c,args[0].replace(/^.*\//,"").replace(/\.yaml$/,"")),report=flag("--report");if(report){mkdirSync(dirname(report),{recursive:true});writeFileSync(report,htmlReport(v,[],undefined,c));}print(v);process.exitCode=exitFor(v.status,args.includes("--fail-on-warn"));}
else if(cmd==="guard"){const p=policy(args[0]),cap=extract(req("--source")),out=flag("--out")||"output/generated-guard.ts",c=loadCatalog();assertAttestableCapabilities(cap,p);mkdirSync(dirname(out),{recursive:true});writeFileSync(out,generatedGuardSource(p,(await import("./arsenallint.ts")).digest(cap),c));print({guard:out});}
else if(cmd==="replay"){const p=policy(args[0]);print(replayProof(p,args[1]));}
else if(cmd==="keygen"){const dir=flag("--out")||"output/keys";mkdirSync(dir,{recursive:true});const keys=keygenFiles(dir,args.includes("--force"));print({public_key:keys.publicKeyPath});}
else if(cmd==="attest"){const p=policy(args[0]),source=req("--source"),trace=req("--trace"),cap=extract(source),catalog=loadCatalog(),verdict=check(p,catalog,"attest"),findings=consistency(p,cap);let capabilityError:string|undefined;try{assertAttestableCapabilities(cap,p);}catch(error){capabilityError=(error as Error).message;}if(verdict.status!=="PASS"||findings.length||capabilityError){print({verdict,consistency_findings:findings,capability_error:capabilityError,receipt:null});process.exitCode=1;}else{const replayResult=replayProof(p,trace),signed=receipt(p,cap,verdict,replayResult,readFileSync(req("--private-key"),"utf8"),catalog,sourceBinding(source).commit,fileDigest(source));const out=flag("--out")||"output/receipt.json";mkdirSync(dirname(out),{recursive:true});writeFileSync(out,JSON.stringify(signed,null,2));print({verdict,receipt:out});}}
else if(cmd==="verify"){const p=policy(req("--policy")),source=req("--source"),trace=flag("--trace")||"fixtures/traces/adversarial.jsonl";let cap:any,commit="unavailable",sourceDigest="unavailable",sourceError:string|undefined;try{cap=extract(source);sourceDigest=fileDigest(source);}catch(error){sourceError=`source capability input unavailable: ${(error as Error).message}`;cap={roles:[],runtime:{},guardrails:{},network_tools:[],code_exec_tools:[],approval_wrappers:[],evidence:[{file:source,line:0,kind:"unknown",detail:sourceError}],unsupported:[sourceError]};}try{commit=sourceBinding(source).commit;}catch(error){sourceError=sourceError||`source capability input unavailable: ${(error as Error).message}`;}const result=verifyReceipt(JSON.parse(readFileSync(args[0],"utf8")),readFileSync(req("--public-key"),"utf8"),{policy:p,capability:cap,replay:replayProof(p,trace),catalog:loadCatalog(),sourceCommit:commit,sourceDigest});if(sourceError)result.reasons.unshift(sourceError);print(result);process.exitCode=result.verified?0:1;}
else if(cmd==="gate"){const p=policy(req("--policy")),cap=extract(req("--source")),v=check(p,loadCatalog(),"gate"),f=consistency(p,cap);print({verdict:v,consistency_findings:f});process.exitCode=v.status==="PASS"&&!f.length?0:1;}
else if(cmd==="demo"){mkdirSync("output/demo-keys",{recursive:true});const p=policy("fixtures/pass.yaml"),c=loadCatalog(),v=check(p,c,"pass"),unsafe=extract("examples/unsafe-agent.ts"),cap=extract("examples/hardened-agent.ts"),t=replayProof(p,"fixtures/traces/adversarial.jsonl"),keys=keygenFiles("output/demo-keys",true),commit=sourceBinding("examples/hardened-agent.ts").commit,sourceDigest=fileDigest("examples/hardened-agent.ts"),signed=receipt(p,cap,v,t,readFileSync(keys.privateKeyPath,"utf8"),c,commit,sourceDigest),verified=verifyReceipt(signed,readFileSync(keys.publicKeyPath,"utf8"),{policy:p,capability:cap,replay:t,catalog:c,sourceCommit:commit,sourceDigest}),d=diff(unsafe,cap);mkdirSync("output",{recursive:true});writeFileSync("output/demo-receipt.json",JSON.stringify(signed,null,2));writeFileSync("output/arsenallint-report.html",htmlReport(v,t,cap,c,verified,d));print({verdict:v.status,diff:d,replay:t,receipt_verification:verified,report:"output/arsenallint-report.html"});}
else throw new Error("arsenallint doctor|extract|diff|check|guard|replay|keygen|attest|verify|gate|demo"); }catch(error){console.error((error as Error).message);process.exitCode=2;}
