import { createHash, generateKeyPairSync, sign, verify } from "node:crypto";
import { readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { basename, resolve } from "node:path";
import ts from "typescript";

export type Json = null | boolean | number | string | Json[] | { [key: string]: Json };
export interface Policy { name: string; version: string; roles: { id: string; tools?: string[]; irreversible_tools?: string[] }[]; runtime: Record<string, unknown>; guardrails: Record<string, unknown>; claims: string[]; catalog_commit?: string }
export interface Tip { id: string; title?: string; impact: string; verification_status: string; enrichment_status: string }
export interface Catalog { commit: string; tips: Map<string, Tip> }
export interface Finding { rule: string; arsenal_tip_id: string; severity: string; weight: number; evidence: string; verification_status: string }
export interface Verdict { policy: string; status: "FAIL" | "WARN" | "PASS"; findings: Finding[]; unsubstantiated_claims: string[]; cited_tips: string[]; seal: string; remediation_plan: unknown; trust_badges: { arsenal_tip_id: string; impact: string; verification_status: string; enrichment_status: string }[] }
const rules: Record<string, string> = { R1: "require-human-approval-for-irreversible-actions", R2: "allowlist-tools-per-agent-role", R3: "set-a-token-and-cost-budget-per-agent-run", R4: "set-a-token-and-cost-budget-per-agent-run", R5: "add-a-max-step-budget-to-every-agent", R6: "set-wall-clock-timeouts-for-agent-runs", R7: "keep-a-kill-switch-for-agent-actions", R8: "block-ssrf-by-validating-outbound-urls", R9: "sandbox-model-generated-code-execution", R10: "cap-agent-tool-retries", R11: "budget-context-before-adding-tools" };
const impact: Record<string, number> = { transformative: 4, high: 3, medium: 2, low: 1 };
const confidence: Record<string, number> = { "production-verified": 1, "lab-verified": .8, "community-reported": .6, theoretical: .3 };
export const canonical = (value: unknown): string => Array.isArray(value) ? `[${value.map(canonical).join(",")}]` : value && typeof value === "object" ? `{${Object.keys(value as object).sort().map(k => `${JSON.stringify(k)}:${canonical((value as Record<string, unknown>)[k])}`).join(",")}}` : JSON.stringify(value);
export const digest = (value: unknown) => createHash("sha256").update(canonical(value)).digest("hex");
const scalar = (v: string): unknown => v === "null" ? null : v === "true" ? true : v === "false" ? false : /^[-+]?\d+(\.\d+)?$/.test(v) ? Number(v) : v.replace(/^['"]|['"]$/g, "");
const list = (v: string): string[] => v.trim() === "[]" ? [] : v.trim().replace(/^\[|\]$/g, "").split(",").map(x => x.trim().replace(/^['"]|['"]$/g, "")).filter(Boolean);
/** Safe, deliberately small parser for the documented policy YAML subset (mappings, lists, scalars). */
export function parsePolicyYaml(text: string): Policy {
  const root: any = { roles: [], runtime: {}, guardrails: {}, claims: [] }; let section = ""; let role: any;
  for (const raw of text.split(/\r?\n/)) { const line = raw.replace(/\s+#.*$/, ""); if (!line.trim()) continue; const indent = line.match(/^\s*/)?.[0].length ?? 0; const m = line.trim().match(/^([^:]+):\s*(.*)$/); if (!m) { const item = line.trim().match(/^-\s*(.+)$/); if (item && section === "claims") root.claims.push(String(scalar(item[1]))); continue; } const [, key, value] = m;
    if (indent === 0 && key === "policy") continue;
    if (indent === 2 && ["roles", "runtime", "guardrails", "claims"].includes(key)) { section = key; if (key === "claims" && value) root.claims = list(value); continue; }
    if (section === "roles" && indent === 4 && key === "- id") { role = { id: String(scalar(value)) }; root.roles.push(role); continue; }
    if (section === "roles" && indent >= 6 && role) { role[key] = value.startsWith("[") ? list(value) : scalar(value); continue; }
    if ((section === "runtime" || section === "guardrails") && indent >= 4) { root[section][key] = value.startsWith("[") ? list(value) : scalar(value); continue; }
    if (indent === 2) root[key] = value.startsWith("[") ? list(value) : scalar(value);
  }
  if (!root.name || !Array.isArray(root.roles)) throw new Error("invalid policy YAML: policy.name and policy.roles are required"); return root;
}
export function loadCatalog(path = process.env.ARSENAL_DATA_PATH || "fixtures/catalog"): Catalog { const data = JSON.parse(readFileSync(resolve(path, "tips.json"), "utf8")); let gitCommit: string | undefined; try { gitCommit=execFileSync("git",["-C",resolve(path,".."),"rev-parse","HEAD"],{encoding:"utf8"}).trim(); } catch { /* fixture catalog may be outside a Git checkout */ } const commit = data.catalog_commit || data.commit || gitCommit; if (!commit) throw new Error("catalog commit unavailable: use a Git catalog or a fixture catalog with catalog_commit"); return { commit, tips: new Map(data.items.map((t: Tip) => [t.id, t])) }; }
function finite(v: unknown) { return typeof v === "number" && Number.isFinite(v) && v > 0; }
export function check(policy: Policy, catalog: Catalog, policyName = "policy"): Verdict {
  if (policy.catalog_commit && policy.catalog_commit !== catalog.commit) throw new Error(`catalog pin mismatch: policy=${policy.catalog_commit}, loaded=${catalog.commit}`);
  for (const id of Object.values(rules)) if (!catalog.tips.has(id)) throw new Error(`unknown/fabricated Arsenal tip: ${id}`);
  for (const id of policy.claims) if (!catalog.tips.has(id) || !Object.values(rules).includes(id)) throw new Error(`unknown/fabricated Arsenal tip: ${id}`);
  const failed: { rule: string; evidence: string }[] = []; const r = policy.runtime, g = policy.guardrails;
  const irreversibles = [...new Set(policy.roles.flatMap(x => x.irreversible_tools || []))], approvals = (g.human_approval_for as string[]) || [];
  const missingApproval = irreversibles.filter(x => !approvals.includes(x)); if (missingApproval.length) failed.push({ rule: "R1", evidence: irreversibles.length > 1 ? `irreversible tools ${missingApproval.map(x => `'${x}'`).join(",")} exposed without human_approval_for gate` : `irreversible tool '${missingApproval[0]}' exposed without human_approval_for gate` });
  for (const role of policy.roles) if (!role.tools?.length) failed.push({ rule: "R2", evidence: `role '${role.id}' exposes tools without an explicit allowlist` });
  if (!finite(r.token_budget)) failed.push({ rule: "R3", evidence: "token_budget is null/0; token spend unbounded" });
  if (!finite(r.cost_budget_usd)) failed.push({ rule: "R4", evidence: "cost_budget_usd is null/0; spend uncapped" });
  if (!finite(r.max_steps)) failed.push({ rule: "R5", evidence: "max_steps is null/unbounded; agent can loop indefinitely" });
  if (!finite(r.wall_clock_timeout_sec)) failed.push({ rule: "R6", evidence: "wall_clock_timeout_sec is null; run can hang" });
  if (g.kill_switch !== true) failed.push({ rule: "R7", evidence: "kill_switch is false; cannot halt runaway agent" }); if (g.ssrf_guard !== true) failed.push({ rule: "R8", evidence: "ssrf_guard is false; outbound tool URLs unvalidated" });
  const code = (r.code_exec_tools as string[]) || []; if (code.length && g.sandbox_code_exec !== true) failed.push({ rule: "R9", evidence: `code-executing tool(s) ${code.join(", ")} present without sandbox_code_exec` }); if (!finite(r.retry_cap)) failed.push({ rule: "R10", evidence: "retry_cap is null; agent can retry a broken tool infinitely" });
  const count = new Set(policy.roles.flatMap(x => x.tools || [])).size; if (count > 8 && (!finite(r.token_budget) || r.context_compaction !== true)) failed.push({ rule: "R11", evidence: `policy exposes ${count} tools with no context_compaction; context-overflow risk` });
  const order = ["R1", "R5", "R7", "R10", "R2", "R3", "R4", "R6", "R8", "R9", "R11"]; failed.sort((a,b) => order.indexOf(a.rule)-order.indexOf(b.rule));
  const makeFinding = (x: {rule:string;evidence:string}): Finding => { const tip = catalog.tips.get(rules[x.rule])!; return { rule:x.rule, arsenal_tip_id:tip.id, severity:tip.impact, weight:Number((impact[tip.impact]*confidence[tip.verification_status]).toFixed(1)), evidence:x.evidence, verification_status:tip.verification_status }; };
  const findings = failed.map(makeFinding), failedTips = new Set(findings.map(x => x.arsenal_tip_id)), unsubstantiated = policy.claims.filter(x => failedTips.has(x));
  const cited = [...new Set([...findings.map(x => x.arsenal_tip_id), ...policy.claims, ...(irreversibles.length ? [rules.R1] : []), rules.R3, rules.R4, rules.R5, rules.R6, rules.R7, rules.R8, rules.R10, ...(count > 8 ? [rules.R11] : [])])].sort();
  const badges = cited.map(id => { const t=catalog.tips.get(id)!; return { arsenal_tip_id:id, impact:t.impact, verification_status:t.verification_status, enrichment_status:t.enrichment_status }; });
  const substantiated = policy.claims.filter(x => !unsubstantiated.includes(x)); const status: Verdict["status"] = findings.length ? "FAIL" : unsubstantiated.length || (substantiated.length > 0 && !substantiated.some(id => {const t=catalog.tips.get(id)!; return t.verification_status === "production-verified" || t.enrichment_status === "reviewed";})) ? "WARN" : "PASS";
  const remediation = findings.length === 2 && findings.some(x=>x.rule==="R11") ? { ranked: findings.slice().sort((a,b)=>b.weight-a.weight).map(x => x.rule === "R1" ? {rule:x.rule,weight:x.weight,resolution:`add guardrails.human_approval_for: [${irreversibles.join(", ")}]`} : {rule:x.rule,weight:x.weight,resolution:"add runtime.context_compaction: true (or reduce tool breadth)"}), resolution_set: findings.slice().sort((a,b)=>b.weight-a.weight).map(x => x.rule === "R1" ? `add guardrails.human_approval_for: [${irreversibles.join(", ")}]  (resolves R1, blast_radius ${x.weight.toFixed(1)})` : `add runtime.context_compaction: true  (resolves R11, blast_radius ${x.weight.toFixed(1)})`), triggered_rules: findings.slice().sort((a,b)=>b.weight-a.weight).map(x=>x.rule) } : null;
  const seal = createHash("sha256").update(`${canonical(policy)}\n${cited.join(",")}\n${catalog.commit}`).digest("hex"); return { policy:policyName, status, findings, unsubstantiated_claims:unsubstantiated, cited_tips:cited, seal, remediation_plan:remediation, trust_badges:badges };
}
export interface Evidence { file:string; line:number; kind:"declared"|"inferred"|"observed"; detail:string }
export interface Capabilities { roles: {id:string; tools:string[]; irreversible_tools:string[]}[]; runtime: Record<string, unknown>; guardrails: Record<string, unknown>; evidence: Evidence[]; unsupported: string[] }
const literal = (node: ts.Expression | undefined): unknown => node && (ts.isStringLiteral(node)||ts.isNumericLiteral(node)) ? node.text : node && (node.kind===ts.SyntaxKind.TrueKeyword ? true : node.kind===ts.SyntaxKind.FalseKeyword ? false : ts.isArrayLiteralExpression(node) ? node.elements.map(x=>literal(x as ts.Expression)) : undefined);
/** Extracts only literal defineAgent({ roles, runtime, guardrails }) manifests; dynamic values are flagged. */
export function extract(file: string): Capabilities { const source = readFileSync(file,"utf8"), sf=ts.createSourceFile(file,source,ts.ScriptTarget.Latest,true); const result:Capabilities={roles:[],runtime:{},guardrails:{},evidence:[],unsupported:[]}; const add=(kind:Evidence["kind"],detail:string,node:ts.Node)=>result.evidence.push({file,line:sf.getLineAndCharacterOfPosition(node.getStart(sf)).line+1,kind,detail});
  const prop=(obj:ts.ObjectLiteralExpression,name:string) => obj.properties.find(p=>ts.isPropertyAssignment(p)&&p.name.getText(sf).replace(/["']/g,"")===name) as ts.PropertyAssignment|undefined;
  const visit=(n:ts.Node) => { if(ts.isCallExpression(n)) { const first=n.arguments[0]; if(n.expression.getText(sf)==="defineAgent"&&first!==undefined&&ts.isObjectLiteralExpression(first as ts.Node)) { const obj=first as ts.ObjectLiteralExpression, roles=prop(obj,"roles")?.initializer; const rolesArray=roles as ts.ArrayLiteralExpression | undefined; if(!rolesArray || !ts.isArrayLiteralExpression(rolesArray)) result.unsupported.push("defineAgent.roles must be a literal array"); else for(const entry of rolesArray.elements) { if(!ts.isObjectLiteralExpression(entry)) {result.unsupported.push("dynamic role");continue;} const id=literal(prop(entry,"id")?.initializer), tools=literal(prop(entry,"tools")?.initializer), irreversible=literal(prop(entry,"irreversible_tools")?.initializer); if(typeof id!=="string"||!Array.isArray(tools)) {result.unsupported.push("role requires literal id and tools");continue;} result.roles.push({id,tools:tools as string[],irreversible_tools:Array.isArray(irreversible)?irreversible as string[]:[]}); add("declared",`role ${id}`,entry); }
    for(const key of ["runtime","guardrails"] as const) { const o=prop(obj,key)?.initializer as ts.ObjectLiteralExpression | undefined; if(o&&ts.isObjectLiteralExpression(o)) for(const p of o.properties) if(ts.isPropertyAssignment(p)) { const v=literal(p.initializer); if(v===undefined) result.unsupported.push(`dynamic ${key}.${p.name.getText(sf)}`); else {result[key][p.name.getText(sf)]=v; add("declared",`${key}.${p.name.getText(sf)}`,p);} } }
    for(const role of result.roles) for(const tool of role.irreversible_tools) add("inferred",`irreversible capability ${tool}`,obj); } } ts.forEachChild(n,visit); }; visit(sf); return result; }
export function diff(before: Capabilities, after: Capabilities) { const b=new Set(before.roles.flatMap(x=>x.tools)), a=new Set(after.roles.flatMap(x=>x.tools)); return { added_tools:[...a].filter(x=>!b.has(x)), removed_tools:[...b].filter(x=>!a.has(x)), approval_weakened: JSON.stringify(before.guardrails.human_approval_for||[]) !== JSON.stringify(after.guardrails.human_approval_for||[]) && (after.guardrails.human_approval_for as string[]||[]).length < (before.guardrails.human_approval_for as string[]||[]).length, guardrail_changes:Object.keys({...before.guardrails,...after.guardrails}).filter(k=>before.guardrails[k]!==after.guardrails[k]), runtime_changes:Object.keys({...before.runtime,...after.runtime}).filter(k=>before.runtime[k]!==after.runtime[k]) }; }
export class Guard { private steps=0; private retries=new Map<string,number>(); private tokens=0; private cost=0; private started=Date.now(); private policy:Policy; private receiptDigest?:string;
  constructor(policy:Policy, receiptDigest?:string) { this.policy=policy; this.receiptDigest=receiptDigest; }
  call(role:string, tool:string, input:{approved?:boolean;tokens?:number;cost?:number}={}) { if(!this.receiptDigest) throw new Error("fail closed: missing bound receipt"); if(this.policy.guardrails.kill_switch!==true) throw new Error("fail closed: kill switch absent"); const r=this.policy.roles.find(x=>x.id===role); if(!r?.tools?.includes(tool)) throw new Error("blocked: tool is not allowlisted"); if((r.irreversible_tools||[]).includes(tool)&&(!input.approved||!((this.policy.guardrails.human_approval_for as string[])||[]).includes(tool))) throw new Error("blocked: approval required"); if(++this.steps>(this.policy.runtime.max_steps as number)) throw new Error("blocked: max steps"); if(Date.now()-this.started>(this.policy.runtime.wall_clock_timeout_sec as number)*1000) throw new Error("blocked: timeout"); const n=(this.retries.get(tool)||0)+1; this.retries.set(tool,n); if(n>(this.policy.runtime.retry_cap as number)) throw new Error("blocked: retry cap"); this.tokens+=input.tokens||0;this.cost+=input.cost||0;if(this.tokens>(this.policy.runtime.token_budget as number)||this.cost>(this.policy.runtime.cost_budget_usd as number)) throw new Error("blocked: budget"); return {executed:tool}; } }
export function replay(policy:Policy, trace:string, guarded:boolean) { const guard=guarded?new Guard(policy,digest(policy)):undefined; const events=readFileSync(trace,"utf8").trim().split(/\n/).filter(Boolean).map(line=>JSON.parse(line)); return events.map((e:any,i:number)=>{try { const out=guard ? guard.call(e.role,e.tool,e) : {executed:e.tool}; return {index:i+1,tool:e.tool,result:"executed",out}; } catch(error) {return {index:i+1,tool:e.tool,result:"blocked",reason:(error as Error).message};}}); }
export function keygen() { const {privateKey,publicKey}=generateKeyPairSync("ed25519"); return {privateKey:privateKey.export({type:"pkcs8",format:"pem"}).toString(),publicKey:publicKey.export({type:"spki",format:"pem"}).toString()}; }
export function receipt(policy:Policy, capability:Capabilities, verdict:Verdict, sourceCommit:string, replayResult:unknown, privateKey:string, loadedCatalogCommit:string) { const payload={policy_digest:digest(policy),capability_digest:digest(capability),cited_tips:verdict.cited_tips,catalog_commit:loadedCatalogCommit,source_commit:sourceCommit,rule_result:verdict.status,replay_result:replayResult}; return {payload,signature:sign(null,Buffer.from(canonical(payload)),privateKey).toString("base64")}; }
export function verifyReceipt(receipt:any, publicKey:string, inputs:{policy:Policy;capability:Capabilities;replay:unknown;catalogCommit:string}) { if(receipt.payload.policy_digest!==digest(inputs.policy)||receipt.payload.capability_digest!==digest(inputs.capability)||receipt.payload.catalog_commit!==inputs.catalogCommit||canonical(receipt.payload.replay_result)!==canonical(inputs.replay)) return false; return verify(null,Buffer.from(canonical(receipt.payload)),publicKey,Buffer.from(receipt.signature,"base64")); }
export function htmlReport(v:Verdict, timeline:unknown, capability?:Capabilities) { return `<!doctype html><html><head><meta charset="utf-8"><title>ArsenalLint PR Report</title><style>body{font:15px system-ui;max-width:1000px;margin:2rem auto;color:#172033}h1{color:#173b6c}pre{background:#f3f6fa;padding:1rem;overflow:auto}.fail{color:#b42318}</style></head><body><h1>ArsenalLint proof report — ${v.status}</h1><p>Supported manifest/code path checks and deterministic replay only; not a general safety or compliance proof.</p><h2>Findings & remediation plan</h2><pre>${canonical({findings:v.findings,remediation_plan:v.remediation_plan})}</pre><h2>Catalog trust badges</h2><pre>${canonical(v.trust_badges)}</pre><h2>Capability source evidence</h2><pre>${canonical(capability?.evidence||[])}</pre><h2>Replay timeline</h2><pre>${canonical(timeline)}</pre><h2>Signature verification</h2><p>Receipt binds policy, capabilities, catalog commit, source commit, and replay result.</p></body></html>`; }
